### ISSUE TITLE
咋搜索自己想要下载的小说？

### ISSUE THREAD

**Issue by qidouhai** [Rcrwrate/Crawler#1]

**Comment by Rcrwrate** [comment]
啊这，你这个iss问的幻海图书馆的问题吧，下次去[这](https://github.com/Rcrwrate/H/issues)问

文件搜索功能集成在[API服务](https://api.phantom-sea-limited.ltd/release/API/search)里

使用前需要设置[token](https://api.phantom-sea-limited.ltd/release/API/token)，完成人机验证即可

**Comment by Rcrwrate** [comment]
> _No description provided._

啊这，你这个iss问的幻海图书馆的问题吧，下次去[这](https://github.com/Rcrwrate/H/issues)问

文件搜索功能集成在[API服务](https://api.phantom-sea-limited.ltd/release/API/search)里

使用前需要设置[token](https://api.phantom-sea-limited.ltd/release/API/token)，完成人机验证即可

**Comment by Rcrwrate** [comment]
如果问的是这个爬虫的话

对于 **trxs123** ，你之前去那个网站搜就行了，不过那个网站明面上的下载系统貌似关闭了

对于另一个 **imwcr** ，你运行之后，会生成一个txt文件，你直接打开在里面搜就行了
